apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-rules
  namespace: app-dev
  labels:
    app: alertmanager
    environment: dev
    platform: multi-cloud