apiVersion : v1
kind : Namespace
Metadata:
  name : platform
  labels :
    name : platform
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/aduit  : restricted
    pod-security.kubernetes.io/warm   : restricted
    pod-security.kubernetes.io/privileged : restricted
    app.kubernetes.io/part-of : platform
    app.kubernetes.io/managed-by : terraform
    app.kubernetes.io/created-by : harish
    app.kubernetes.io/owner : harish
    app.kubernetes.io/environment : dev
    app.kubernetes.io/component : platform
    app.kubernetes.io/instance : platform
    app.kubernetes.io/version : "1.0"
