apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-nodesjs-ingress
  namespace: app-dev
  labels:
    app: app-nodesjs
    environment: dev
    platform: multi-cloud
spec:
  rules:
  - host: app-nodesjs.example.com
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: app-nodesjs-service
            port:
              number: 80